### PR TITLE
fixed auth related issues

### LINKED ISSUE #53: Add a logic to navigate users after sign up success
Current code does nothing after signing up so I want to add a feature to navigate users once sign up succeed

https://user-images.githubusercontent.com/67321065/258713002-45fbc0a8-75c6-42bf-b0f9-2d63ecf4dbfd.mov

### LINKED ISSUE #89: Show Error message when login failures

### PR DESCRIPTION
**Pull request by Lada496**
### Feature Description
- Added redirect feature after signing up
- Added error message when login/sing up failure
- Added error messages for invalid inputs
- Added logic to check if the submit button is `disabled` or not
Screenshot 2023-10-22 at 20 18 00

Screenshot 2023-10-22 at 20 17 00

### Related Issue
close #89 
close #53 

### Something you want to mention
N/A

### Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

File: src/app/(auth)/signup/page.tsx [hunk 1]
```diff
@@ -57,15 +68,21 @@ const Signup = () => {
...
+          {error && (
+            <Text fw="bold" color={theme.colors.red[0]} mt={3}>
+              {error.message}
+            </Text>
+          )}
           <Box maw={320} mx="auto" style={{ width: "100%" }}>
             <form
-              onSubmit={form.onSubmit((values) =>
+              onSubmit={form.onSubmit((values) => {
+                console.log("run");
```
Comment (keento0809) [inline src/app/(auth)/signup/page.tsx]: @Lada496 We can delete this `console.log` if it's not necessary

File: src/app/(auth)/signup/page.tsx [hunk 2]
```diff
@@ -38,10 +42,17 @@ const Signup = () => {
...
+  });
+
+  // To check if there is no input error
+  const isDisabled = Object.keys(form.errors).length !== 0 ? true : false;
 
-  if (session) {
-    redirect("/");
+  if (userData) {
+    redirect("/login");
   }
```
Comment (keento0809) [inline src/app/(auth)/signup/page.tsx:56]: @Lada496 The reason for redirecting `/login` here is to navigate to the main page (`/`) through login page? 👀

**Review by keento0809 — COMMENTED** [review]
@Lada496 Thank you for working on modification of user authentication! I left some comments so plz take a look when you have time

File: src/app/(auth)/signup/page.tsx (hunk 2 above)
Comment (Lada496) [reply src/app/(auth)/signup/page.tsx:56]: yeah, I thought it was better to navigate users to `/login` instead of `/` because this signup operation does not allow users to log in.

Comment (keento0809) [reply src/app/(auth)/signup/page.tsx:56]: @Lada496 I see, that makes sense!

**Review by keento0809 — APPROVED** [review]

**Comment by SachiGoto** [comment]
@Lada496 LGTM! Thank you so much for enhancing the login and sign-up user experience!

**Review by SachiGoto — APPROVED** [review]
